import { IComment } from "../models/comments";
import { IUser } from "../models/user";
import { IReview } from "../models/review";
import { IAppointment } from "../models/appointment";

export const doctor_gallery: { path: any }[] = [
  { path: "../../assets/img/gallery/pic_1.PNG" },
  { path: "../../assets/img/gallery/pic_2.PNG" },
  { path: "../../assets/img/gallery/pic_3.jpg" },
  { path: "../../assets/img/gallery/pic_4.jpg" },
  { path: "../../assets/img/gallery/pic_5.jpg" },
  { path: "../../assets/img/gallery/pic_6.jpg" },
  { path: "../../assets/img/gallery/pic_7.jpg" },
  { path: "../../assets/img/gallery/pic_8.jpg" },
];

const amal_toumi = "../../assets/img/users/amal_toumi.jpg";
const ahlem_sellami = "../../assets/img/users/ahlem_sellami.jpg";
const mourad_ennour = "../../assets/img/users/mourad_ennour.jpg";
const kamal_ghanmi = "../../assets/img/users/kamal_ghanmi.jpg";

export const comments: IComment[] = [
  {
    id: 1,
    email: "nullam@icloud.com",
    medecinId: 6,
    date: "Apr 29, 2022",
    comment:
      "euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc",
  },
  {
    id: 2,
    email: "aliquam.vulputate.ullamcorper@outlook.ca",
    medecinId: 7,
    date: "Nov 25, 2021",
    comment:
      "Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum",
  },
  {
    id: 3,
    email: "placerat.velit@protonmail.edu",
    medecinId: 8,
    date: "Sep 30, 2022",
    comment:
      "lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu,",
  },
  {
    id: 4,
    email: "suscipit@yahoo.org",
    medecinId: 9,
    date: "Aug 11, 2021",
    comment:
      "quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur",
  },
  {
    id: 5,
    email: "ligula.nullam@protonmail.couk",
    medecinId: 10,
    date: "May 27, 2022",
    comment:
      "semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget",
  },
];

export const users: IUser[] = [
  {
    id: 1,
    firstName: "Candice",
    lastName: "Sanchez",
    email: "varius.1@outlook.net",
    phone: 97181578,
    address: "P.O. Box 720, 2593 Commodo Ave",
    password: "123456",
    role: "admin",
  },
  {
    id: 2,
    firstName: "Urielle",
    lastName: "Johnston",
    email: "non.magna@icloud.edu",
    phone: 55172166,
    address: "P.O. Box 836, 3956 Sollicitudin Av.",
    password: "123456",
    role: "patient",
  },
  {
    id: 3,
    firstName: "Baxter",
    lastName: "Knowles",
    email: "euismod@protonmail.edu",
    phone: 27411772,
    address: "Ap #896-1079 Ornare, St.",
    password: "123456",
    role: "patient",
  },
  {
    id: 4,
    firstName: "Keefe",
    lastName: "Stephens",
    email: "congue.in@google.net",
    phone: 27428180,
    address: "Ap #394-9883 Erat Rd.",
    password: "123456",
    role: "admin",
  },
  {
    id: 5,
    firstName: "Demetrius",
    lastName: "Adams",
    email: "elit.elit.fermentum@outlook.net",
    phone: 55179167,
    address: "Ap #755-5824 Tempus Ave",
    password: "123456",
    role: "patient",
  },
  {
    id: 6,
    firstName: "Candice",
    lastName: "Sabl",
    email: "variu.2s@outlook.net",
    phone: 97181578,
    address: "P.O. Box 720, 2593 Commodo Ave",
    password: "123456",
    role: "medecin",
    gender: "Internists",
    speciality: "Médecine interne",
    fax: 71966469,
    url: "http://medecin.tn",
    medecinPackage: "basic",
  },
  {
    id: 7,
    firstName: "Urielle",
    lastName: "Johnston",
    email: "non.magna@icloud.edu",
    phone: 55172166,
    address: "P.O. Box 836, 3956 Sollicitudin Av.",
    password: "123456",
    role: "medecin",
    gender: "Internists",
    speciality: "Maladies infectieuses",
    fax: 71251265,
    url: "https://doc.com",
    medecinPackage: "gold",
  },
  {
    id: 8,
    firstName: "Baxter",
    lastName: "Knowles",
    email: "euismod@protonmail.edu",
    phone: 27411772,
    address: "Ap #896-1079 Ornare, St.",
    password: "123456",
    role: "medecin",
    gender: "Nephrologists",
    speciality: "Réanimation médicale",
    fax: 71872344,
    url: "https://medecin.tn",
    medecinPackage: "platin",
  },
  {
    id: 9,
    firstName: "Keefe",
    lastName: "Stephens",
    email: "congue.in@google.net",
    phone: 27428180,
    address: "Ap #394-9883 Erat Rd.",
    password: "123456",
    role: "medecin",
    gender: "Nephrologists",
    speciality: "Carcinologie médicale",
    fax: 71123803,
    url: "https://hospi.com",
    medecinPackage: "basic",
  },
  {
    id: 10,
    firstName: "Demetrius",
    lastName: "Adams",
    email: "elit.elit.fermentum@outlook.net",
    phone: 55179167,
    address: "Ap #755-5824 Tempus Ave",
    password: "123456",
    role: "medecin",
    gender: "Cardiologists",
    speciality: "Nutrition et maladies nutritionnelles",
    fax: 71405961,
    url: "http://doc.com",
    medecinPackage: "gold",
  },
];

export const user_requests: IUser[] = [
  {
    id: 1,
    firstName: "Candice",
    lastName: "Sanchez",
    email: "varius@outlook.net",
    phone: 97181578,
    address: "P.O. Box 720, 2593 Commodo Ave",
    password: "123456",
    role: "admin",
  },
  {
    id: 2,
    firstName: "Urielle",
    lastName: "Johnston",
    email: "non.magna@icloud.edu",
    phone: 55172166,
    address: "P.O. Box 836, 3956 Sollicitudin Av.",
    password: "123456",
    role: "medecin",
  },
  {
    id: 3,
    firstName: "Baxter",
    lastName: "Knowles",
    email: "euismod@protonmail.edu",
    phone: 27411772,
    address: "Ap #896-1079 Ornare, St.",
    password: "123456",
    role: "patient",
  },
  {
    id: 4,
    firstName: "Keefe",
    lastName: "Stephens",
    email: "congue.in@google.net",
    phone: 27428180,
    address: "Ap #394-9883 Erat Rd.",
    password: "123456",
    role: "admin",
  },
  {
    id: 5,
    firstName: "Demetrius",
    lastName: "Adams",
    email: "elit.elit.fermentum@outlook.net",
    phone: 55179167,
    address: "Ap #755-5824 Tempus Ave",
    password: "123456",
    role: "medecin",
  },
];

export const reviews: IReview[] = [
  {
    id: 1,
    email: "vitae.semper.egestas@hotmail.net",
    date: "Mar 17, 2023",
    message:
      "egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis",
  },
  {
    id: 2,
    email: "metus.aenean.sed@protonmail.couk",
    date: "Aug 23, 2022",
    message:
      "in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non",
  },
  {
    id: 3,
    email: "duis.mi@google.ca",
    date: "Feb 26, 2023",
    message:
      "odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec,",
  },
  {
    id: 4,
    email: "vitae.nibh.donec@google.edu",
    date: "Mar 23, 2023",
    message:
      "luctus et ultrices posuere cubilia Curae Donec tincidunt. Donec vitae erat vel pede blandit",
  },
  {
    id: 5,
    email: "ante@hotmail.edu",
    date: "Apr 19, 2022",
    message:
      "semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac",
  },
];
export const appointments: IAppointment[] = [
  {
    id: 1,
    patientId: 2,
    medId: 6,
    startDate: new Date(2021, 3, 26, 9, 30),
    endDate: new Date(2021, 3, 26, 11, 30),
  },
  {
    id: 2,
    patientId: 3,
    medId: 6,
    startDate: new Date(2021, 3, 26, 13),
    endDate: new Date(2021, 3, 26, 14),
  },
  {
    id: 3,
    patientId: 3,
    medId: 7,
    startDate: new Date(2021, 3, 27, 10),
    endDate: new Date(2021, 3, 27, 11),
  },
  {
    id: 4,
    patientId: 5,
    medId: 8,
    startDate: new Date(2021, 3, 27, 13, 30),
    endDate: new Date(2021, 3, 27, 15),
  },
  {
    id: 5,
    patientId: 2,
    medId: 9,
    startDate: new Date(2021, 3, 26, 15),
    endDate: new Date(2021, 3, 26, 16, 15),
  },
  {
    id: 6,
    patientId: 5,
    medId: 10,
    startDate: new Date(2021, 3, 28, 9, 45),
    endDate: new Date(2021, 3, 28, 12),
  },
  {
    id: 7,
    patientId: 5,
    medId: 6,
    startDate: new Date(2021, 3, 28, 14, 30),
    endDate: new Date(2021, 3, 28, 16, 30),
  },
  {
    id: 8,
    patientId: 3,
    medId: 10,
    startDate: new Date(2021, 3, 27, 15, 30),
    endDate: new Date(2021, 3, 27, 16, 45),
  },
  {
    id: 9,
    patientId: 2,
    medId: 10,
    startDate: new Date(2021, 4, 3, 13),
    endDate: new Date(2021, 4, 3, 15),
  },
  {
    id: 10,
    patientId: 2,
    medId: 7,
    startDate: new Date(2021, 4, 4, 15, 30),
    endDate: new Date(2021, 4, 5),
  },
  {
    id: 11,
    patientId: 5,
    medId: 8,
    startDate: new Date(2021, 3, 30, 10),
    endDate: new Date(2021, 3, 30, 12),
  },
  {
    id: 12,
    patientId: 3,
    medId: 6,
    startDate: new Date(2021, 3, 30, 16, 30),
    endDate: new Date(2021, 3, 30, 18),
  },
  {
    id: 13,
    patientId: 2,
    medId: 10,
    startDate: new Date(2021, 4, 5, 10),
    endDate: new Date(2021, 4, 5, 11, 30),
  },
  {
    id: 14,
    patientId: 2,
    medId: 7,
    startDate: new Date(2021, 3, 30, 14, 30),
    endDate: new Date(2021, 3, 30, 16, 10),
  },
];
export const appointmentRequests: IAppointment[] = [
  {
    id: 1,
    patientId: 2,
    medId: 6,
    startDate: new Date(2021, 3, 26, 9, 30),
    endDate: new Date(2021, 3, 26, 11, 30),
  },
  {
    id: 2,
    patientId: 3,
    medId: 6,
    startDate: new Date(2021, 3, 26, 13),
    endDate: new Date(2021, 3, 26, 14),
  },
  {
    id: 3,
    patientId: 3,
    medId: 7,
    startDate: new Date(2021, 3, 27, 10),
    endDate: new Date(2021, 3, 27, 11),
  },
  {
    id: 4,
    patientId: 5,
    medId: 8,
    startDate: new Date(2021, 3, 27, 13, 30),
    endDate: new Date(2021, 3, 27, 15),
  },
  {
    id: 5,
    patientId: 2,
    medId: 9,
    startDate: new Date(2021, 3, 26, 15),
    endDate: new Date(2021, 3, 26, 16, 15),
  },
  {
    id: 6,
    patientId: 5,
    medId: 10,
    startDate: new Date(2021, 3, 28, 9, 45),
    endDate: new Date(2021, 3, 28, 12),
  },
  {
    id: 7,
    patientId: 5,
    medId: 6,
    startDate: new Date(2021, 3, 28, 14, 30),
    endDate: new Date(2021, 3, 28, 16, 30),
  },
  {
    id: 8,
    patientId: 3,
    medId: 10,
    startDate: new Date(2021, 3, 27, 15, 30),
    endDate: new Date(2021, 3, 27, 16, 45),
  },
  {
    id: 9,
    patientId: 2,
    medId: 10,
    startDate: new Date(2021, 4, 3, 13),
    endDate: new Date(2021, 4, 3, 15),
  },
  {
    id: 10,
    patientId: 2,
    medId: 7,
    startDate: new Date(2021, 4, 4, 15, 30),
    endDate: new Date(2021, 4, 5),
  },
  {
    id: 11,
    patientId: 5,
    medId: 8,
    startDate: new Date(2021, 3, 30, 10),
    endDate: new Date(2021, 3, 30, 12),
  },
  {
    id: 12,
    patientId: 3,
    medId: 6,
    startDate: new Date(2021, 3, 30, 16, 30),
    endDate: new Date(2021, 3, 30, 18),
  },
  {
    id: 13,
    patientId: 2,
    medId: 10,
    startDate: new Date(2021, 4, 5, 10),
    endDate: new Date(2021, 4, 5, 11, 30),
  },
  {
    id: 14,
    patientId: 2,
    medId: 7,
    startDate: new Date(2021, 3, 30, 14, 30),
    endDate: new Date(2021, 3, 30, 16, 10),
  },
];

export const specialities = [
  "Médecine interne",
  "Maladies infectieuses",
  "Réanimation médicale",
  "Carcinologie médicale",
  "Nutrition et maladies nutritionnelles",
  "Hématologie clinique",
  "Endocrinologie",
  "Cardiologie",
  "Néphrologie",
  "Neurologie",
  "Pneumologie",
  "Rhumatologie",
  "Gastro-entérologie",
  "Médecine physique",
  "rééducation et réadaptation fonctionnelle",
  "Dermatologie",
  "Pédiatrie",
  "Psychiatrie",
  "Pédopsychiatrie",
  "Imagerie médicale",
  "Radiothérapie carcinologique",
  "Médecine légale",
  "Médecine du travail",
  "Médecine préventive et communautaire",
  "Anesthésie-réanimation",
  "Anatomie et cytologie pathologique",
  "Médecine d'urgence",
];
